import scrapy

class SurveyUSA2TablesSpider(scrapy.Spider):
	name = "surveyusa2"

	def start_requests(self):
		urls = ['http://www.surveyusa.com/client/PollReport_main.aspx?g=5128ee79-1b59-4146-bf80-54906bb24d4b&d=1',]

		for url in urls:
			yield scrapy.Request(url=url, callback=self.parse)

	def parse(self, response):
		for row in response.xpath('//*[@class="qtable"]//tr'):
			yield {
				'c1' : row.xpath('td[1]//text()').extract_first(),
				'c2' : row.xpath('td[2]//text()').extract_first(),
				'c3' : row.xpath('td[3]//text()').extract_first(),
				'c4' : row.xpath('td[4]//text()').extract_first(),
				'c5' : row.xpath('td[5]//text()').extract_first(),
				'c6' : row.xpath('td[6]//text()').extract_first(),
				'c7' : row.xpath('td[7]//text()').extract_first(),
				'c8' : row.xpath('td[8]//text()').extract_first(),
				'c9' : row.xpath('td[9]//text()').extract_first(),
				'c10' : row.xpath('td[10]//text()').extract_first(),
				'c11' : row.xpath('td[11]//text()').extract_first(),
				'c12' : row.xpath('td[12]//text()').extract_first(),
				'c13' : row.xpath('td[13]//text()').extract_first(),
				'c14' : row.xpath('td[14]//text()').extract_first(),
				'c15' : row.xpath('td[15]//text()').extract_first(),
				'c16' : row.xpath('td[16]//text()').extract_first(),
				'c17' : row.xpath('td[17]//text()').extract_first(),
				'c18' : row.xpath('td[18]//text()').extract_first(),
				'c19' : row.xpath('td[19]//text()').extract_first(),
				'c20' : row.xpath('td[20]//text()').extract_first(),
				'c21' : row.xpath('td[21]//text()').extract_first(),
				'c22' : row.xpath('td[22]//text()').extract_first(),
				'c23' : row.xpath('td[23]//text()').extract_first(),
				'c24' : row.xpath('td[24]//text()').extract_first(),
				'c25' : row.xpath('td[25]//text()').extract_first(),
				'c26' : row.xpath('td[26]//text()').extract_first(),
				'c27' : row.xpath('td[27]//text()').extract_first(),
				'c28' : row.xpath('td[28]//text()').extract_first(),
				'c29' : row.xpath('td[29]//text()').extract_first(),
				'c30' : row.xpath('td[30]//text()').extract_first(),
				'c31' : row.xpath('td[31]//text()').extract_first(),
				'c32' : row.xpath('td[32]//text()').extract_first(),
				'c33' : row.xpath('td[33]//text()').extract_first(),
				'c34' : row.xpath('td[34]//text()').extract_first(),
				'c35' : row.xpath('td[35]//text()').extract_first(),
				'c36' : row.xpath('td[36]//text()').extract_first(),
				'c37' : row.xpath('td[37]//text()').extract_first(),
				'c38' : row.xpath('td[38]//text()').extract_first(),
				'c39' : row.xpath('td[39]//text()').extract_first(),
				'c40' : row.xpath('td[40]//text()').extract_first(),
				'c41' : row.xpath('td[41]//text()').extract_first(),
				'c42' : row.xpath('td[42]//text()').extract_first(),
				'c43' : row.xpath('td[43]//text()').extract_first(),
				'c44' : row.xpath('td[44]//text()').extract_first(),
				'c45' : row.xpath('td[45]//text()').extract_first(),
				'c46' : row.xpath('td[46]//text()').extract_first(),
				'c47' : row.xpath('td[47]//text()').extract_first(),
				'c48' : row.xpath('td[48]//text()').extract_first(),
				'c49' : row.xpath('td[49]//text()').extract_first(),
				'c50' : row.xpath('td[50]//text()').extract_first(),
				'c51' : row.xpath('td[51]//text()').extract_first(),
				'c52' : row.xpath('td[52]//text()').extract_first(),
				'c53' : row.xpath('td[53]//text()').extract_first(),
				'c54' : row.xpath('td[54]//text()').extract_first(),
				'c55' : row.xpath('td[55]//text()').extract_first(),
				'c56' : row.xpath('td[56]//text()').extract_first(),
				'c57' : row.xpath('td[57]//text()').extract_first(),
				'c58' : row.xpath('td[58]//text()').extract_first(),
				'c59' : row.xpath('td[59]//text()').extract_first(),
				'c60' : row.xpath('td[60]//text()').extract_first(),
				'c61' : row.xpath('td[61]//text()').extract_first(),
				'c62' : row.xpath('td[62]//text()').extract_first(),
				'c63' : row.xpath('td[63]//text()').extract_first(),
				'c64' : row.xpath('td[64]//text()').extract_first(),
				'c65' : row.xpath('td[65]//text()').extract_first(),
				'c66' : row.xpath('td[66]//text()').extract_first(),
				'c67' : row.xpath('td[67]//text()').extract_first(),
				'c68' : row.xpath('td[68]//text()').extract_first(),
				'c69' : row.xpath('td[69]//text()').extract_first(),
				'c70' : row.xpath('td[70]//text()').extract_first(),
				'c71' : row.xpath('td[71]//text()').extract_first(),
				'c72' : row.xpath('td[72]//text()').extract_first(),
				'c73' : row.xpath('td[73]//text()').extract_first(),
				'c74' : row.xpath('td[74]//text()').extract_first(),
				'c75' : row.xpath('td[75]//text()').extract_first(),
				'c76' : row.xpath('td[76]//text()').extract_first(),
                'c77' : row.xpath('td[77]//text()').extract_first(),
			}
